formation_costmap:
  # Die beiden hier muss ich nicht variabel machen, andere müssen sich danach richten, woher sie die Infos bekommen
  # formation_footprint_topic_name: formation_footprint
  # formation_centre_topic_name: formation_centre
  formation_robots:
    robot0:
      master: true
      namespace: /robot0
      robot_outline: [[0.506,-0.32],[0.506,0.32],[-0.454,0.32],[-0.454,-0.32]]
      robot_pose_topic: robot_pose 
    robot1:
      namespace: /robot1
      robot_outline: [[0.506,-0.32],[0.506,0.32],[-0.454,0.32],[-0.454,-0.32]]
      robot_pose_topic: robot_pose