---
float32 minimal_encloring_circle_radius
geometry_msgs/Pose2D formation_centre
# This footprint has its centre located at 0/0. So this is not the actual position in the map, only defines the shape
geometry_msgs/Polygon formation_footprint